### ISSUE TITLE
with rpm - no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by trel** [dnbert/prm#48]
This could be user error - I'm just getting started with `prm`.

I've got the deb side of the house working (using -d), but have not yet been successful with an rpm file.

```
[dltest]$ ruby --version
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

[dltest]$ ls
bind-utils-9.8.2-0.37.rc1.el6_7.2.x86_64.rpm

[dltest]$ prm -t rpm -a x86_64 -r centos6 -p pool
/home/trel/.rvm/gems/ruby-2.2.1/gems/prm-0.2.12/lib/prm/rpm.rb:116:in `initialize': no implicit conversion of String into Integer (TypeError)
        from /home/trel/.rvm/gems/ruby-2.2.1/gems/prm-0.2.12/lib/prm/rpm.rb:116:in `open'
        from /home/trel/.rvm/gems/ruby-2.2.1/gems/prm-0.2.12/lib/prm/rpm.rb:116:in `block (2 levels) in build_rpm_repo'
        from /home/trel/.rvm/gems/ruby-2.2.1/gems/peach-0.5.1/lib/peach.rb:22:in `block (2 levels) in peach'
        from /home/trel/.rvm/gems/ruby-2.2.1/gems/peach-0.5.1/lib/peach.rb:22:in `each'
        from /home/trel/.rvm/gems/ruby-2.2.1/gems/peach-0.5.1/lib/peach.rb:22:in `block in peach'
        from /home/trel/.rvm/gems/ruby-2.2.1/gems/peach-0.5.1/lib/peach.rb:13:in `block (2 levels) in _peach_run'
```

Without the -d option (#38), is this the correct usage?  The RPM file must be in the pwd?

**Comment by dnbert** [comment]
Doesn't look like the templates directory is getting passed to the library! I'm working on a patch now, then I'll upload to rubygems!

**Comment by dnbert** [comment]
https://github.com/dnbert/prm/commit/b432ac94047f61230efaef01276c08ca1c3475d7 should fix it! Looks like I was being a bit lazy with my File options. I haven't been using the RPM feature set much, please let me know if you find other bugs

**Comment by trel** [comment]
Excellent - I confirm the repo is created.

However, I don't see any file-specific information in the created repository.  The files all appear to be empty containers...

```
[dltest]$ find pool
pool
pool/centos6
pool/centos6/x86_64
pool/centos6/x86_64/repodata
pool/centos6/x86_64/repodata/20ac69ae1e210bdf522433c8cad646d9698bc6c59ab8cfd436918199eca421e8-primary.xml
pool/centos6/x86_64/repodata/48a906b2145a73b46728252e90403e200e83f99e4be457ed24fc6a6336ba2707-filelists.xml
pool/centos6/x86_64/repodata/6aa42dc102bb262bdbe72ce84206c5e990c25a6c1e8bb115e8a0e0c464340a29-other.xml
pool/centos6/x86_64/repodata/repomd.xml

[dltest]$ ls -l pool/centos6/x86_64/repodata/
total 24
-rw-rw-r--. 1 trelvb trelvb  169 Aug 24 16:26 20ac69ae1e210bdf522433c8cad646d9698bc6c59ab8cfd436918199eca421e8-primary.xml
-rw-rw-r--. 1 trelvb trelvb  127 Aug 24 16:26 48a906b2145a73b46728252e90403e200e83f99e4be457ed24fc6a6336ba2707-filelists.xml
-rw-rw-r--. 1 trelvb trelvb  123 Aug 24 16:26 6aa42dc102bb262bdbe72ce84206c5e990c25a6c1e8bb115e8a0e0c464340a29-other.xml
-rw-rw-r--. 1 trelvb trelvb 1787 Aug 24 16:26 repomd.xml

```

Can you share an example of what success should look like?   Thanks!
